name: Validate Action

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: Run actionlint
        uses: rhysd/actionlint@v1

      - name: Run Tests
        run: |
          # Add any test commands here if applicable
          echo "Add tests for your action here"
